# Generated by Django 4.1.2 on 2022-10-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("candidate_id", models.AutoField(primary_key=True, serialize=False)),
                ("candidate_name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_reason", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                ("election_id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=100)),
                (
                    "elections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                ("voter_id", models.AutoField(primary_key=True, serialize=False)),
                ("voter_password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.candidate",
                    ),
                ),
                (
                    "election_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.election",
                    ),
                ),
                (
                    "voter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.voter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="candidate_election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="elections.election"
            ),
        ),
    ]
