# Generated by Django 4.1.2 on 2022-10-21 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="voters",
            field=models.ManyToManyField(
                related_name="elections", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
